import React, { createContext, useContext, useState } from 'react'

export type Lang = 'zh-TW' | 'zh-CN' | 'en'

const translations: Record<Lang, Record<string, string>> = {
  'zh-TW': {
    'app.name': '香港交易所',
    'app.subtitle': 'HKEX Trading Center',
    'nav.home': '首頁',
    'nav.market': '行情',
    'nav.ipo': '新股',
    'nav.news': '資訊',
    'nav.study': '學堂',
    'nav.tools': '工具',
    'nav.about': '關於',
    'nav.service': '客服',
    'nav.account': '我的',
    'nav.favorites': '自選',
    'login.title': '登錄',
    'login.welcome': '歡迎回來',
    'login.phone': '請輸入手機號',
    'login.password': '請輸入密碼',
    'login.button': '登錄',
    'login.register': '立即註冊',
    'register.title': '註冊賬戶',
    'register.name': '設置暱稱',
    'register.password': '設置密碼（6-20位）',
    'register.confirm': '確認密碼',
    'register.invite': '邀請碼（選填）',
    'register.agree': '我已閱讀並同意《用戶服務協議》和《隱私政策》',
    'register.button': '註冊',
    'register.haveAccount': '已有賬號？',
    'recharge.title': '充值',
    'recharge.time': '充值服務時間 09:00-22:00',
    'recharge.balance': '賬戶餘額',
    'recharge.amount': '選擇充值金額',
    'recharge.method': '選擇支付方式',
    'recharge.submit': '聯繫客服充值',
    'withdraw.title': '提現',
    'withdraw.balance': '可用餘額',
    'withdraw.card': '選擇提現銀行卡',
    'withdraw.amount': '提現金額',
    'withdraw.all': '全部提現',
    'withdraw.submit': '提交提現申請',
    'position.title': '持倉管理',
    'position.total': '總持倉市值',
    'position.add': '加倉',
    'position.reduce': '減倉',
    'position.close': '平倉',
    'account.title': '賬戶管理',
    'account.nickname': '暱稱',
    'account.phone': '手機號',
    'account.changePw': '修改密碼',
    'account.realName': '實名認證',
    'account.logout': '退出登錄',
    'auth.title': '實名認證',
    'auth.unverified': '未認證',
    'auth.pending': '審核中',
    'auth.verified': '已認證',
    'auth.rejected': '已駁回',
    'auth.name': '真實姓名',
    'auth.idCard': '身份證號',
    'auth.front': '身份證正面',
    'auth.back': '身份證反面',
    'auth.hold': '手持身份證',
    'auth.submit': '提交審核',
    'bank.title': '銀行卡管理',
    'bank.add': '添加銀行卡',
    'bank.default': '默認',
    'footer.about': '關於我們',
    'footer.trade': '交易服務',
    'footer.help': '幫助中心',
    'footer.contact': '聯繫我們',
    'footer.copyright': '© 2026 香港交易所 版權所有',
    'footer.risk': '投資有風險，入市需謹慎',
    'footer.icp': 'ICP備案號：粵ICP備2026123456號',
    'footer.license': '香港證券及期貨事務監察委員會持牌法團',
    'market.title': '行情中心',
    'market.search': '搜索股票代碼或名稱',
    'stock.buy': '買入',
    'stock.sell': '賣出',
    'stock.favorite': '自選',
    'news.title': '資訊中心',
    'ipo.title': '新股IPO',
    'study.title': '投資者學堂',
    'tools.title': '智能工具箱',
    'about.title': '關於平台',
    'service.title': '在線客服',
    'points.title': '積分商城',
    'asset.title': '資產錢包',
    'index.indices': '核心指數',
    'index.ranking': '行情榜單',
    'index.news': '7×24 快訊',
    'index.calendar': '交易日曆',
    'index.quick': '快捷入口',
  },
  'zh-CN': {
    'app.name': '香港交易所',
    'app.subtitle': 'HKEX Trading Center',
    'nav.home': '首页',
    'nav.market': '行情',
    'nav.ipo': '新股',
    'nav.news': '资讯',
    'nav.study': '学堂',
    'nav.tools': '工具',
    'nav.about': '关于',
    'nav.service': '客服',
    'nav.account': '我的',
    'nav.favorites': '自选',
    'login.title': '登录',
    'login.welcome': '欢迎回来',
    'login.phone': '请输入手机号',
    'login.password': '请输入密码',
    'login.button': '登录',
    'login.register': '立即注册',
    'register.title': '注册账户',
    'register.name': '设置昵称',
    'register.password': '设置密码（6-20位）',
    'register.confirm': '确认密码',
    'register.invite': '邀请码（选填）',
    'register.agree': '我已阅读并同意《用户服务协议》和《隐私政策》',
    'register.button': '注册',
    'register.haveAccount': '已有账号？',
    'recharge.title': '充值',
    'recharge.time': '充值服务时间 09:00-22:00',
    'recharge.balance': '账户余额',
    'recharge.amount': '选择充值金额',
    'recharge.method': '选择支付方式',
    'recharge.submit': '联系客服充值',
    'withdraw.title': '提现',
    'withdraw.balance': '可用余额',
    'withdraw.card': '选择提现银行卡',
    'withdraw.amount': '提现金额',
    'withdraw.all': '全部提现',
    'withdraw.submit': '提交提现申请',
    'position.title': '持仓管理',
    'position.total': '总持仓市值',
    'position.add': '加仓',
    'position.reduce': '减仓',
    'position.close': '平仓',
    'account.title': '账户管理',
    'account.nickname': '昵称',
    'account.phone': '手机号',
    'account.changePw': '修改密码',
    'account.realName': '实名认证',
    'account.logout': '退出登录',
    'auth.title': '实名认证',
    'auth.unverified': '未认证',
    'auth.pending': '审核中',
    'auth.verified': '已认证',
    'auth.rejected': '已驳回',
    'auth.name': '真实姓名',
    'auth.idCard': '身份证号',
    'auth.front': '身份证正面',
    'auth.back': '身份证反面',
    'auth.hold': '手持身份证',
    'auth.submit': '提交审核',
    'bank.title': '银行卡管理',
    'bank.add': '添加银行卡',
    'bank.default': '默认',
    'footer.about': '关于我们',
    'footer.trade': '交易服务',
    'footer.help': '帮助中心',
    'footer.contact': '联系我们',
    'footer.copyright': '© 2026 香港交易所 版权所有',
    'footer.risk': '投资有风险，入市需谨慎',
    'footer.icp': 'ICP备案号：粤ICP备2026123456号',
    'footer.license': '香港证券及期货事务监察委员会持牌法团',
    'market.title': '行情中心',
    'market.search': '搜索股票代码或名称',
    'stock.buy': '买入',
    'stock.sell': '卖出',
    'stock.favorite': '自选',
    'news.title': '资讯中心',
    'ipo.title': '新股IPO',
    'study.title': '投资者学堂',
    'tools.title': '智能工具箱',
    'about.title': '关于平台',
    'service.title': '在线客服',
    'points.title': '积分商城',
    'asset.title': '资产钱包',
    'index.indices': '核心指数',
    'index.ranking': '行情榜单',
    'index.news': '7×24 快讯',
    'index.calendar': '交易日历',
    'index.quick': '快捷入口',
  },
  'en': {
    'app.name': 'Hong Kong Exchange',
    'app.subtitle': 'HKEX Trading Center',
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.ipo': 'IPO',
    'nav.news': 'News',
    'nav.study': 'Study',
    'nav.tools': 'Tools',
    'nav.about': 'About',
    'nav.service': 'Service',
    'nav.account': 'Account',
    'nav.favorites': 'Favorites',
    'login.title': 'Login',
    'login.welcome': 'Welcome Back',
    'login.phone': 'Phone Number',
    'login.password': 'Password',
    'login.button': 'Login',
    'login.register': 'Register',
    'register.title': 'Register',
    'register.name': 'Nickname',
    'register.password': 'Password (6-20 chars)',
    'register.confirm': 'Confirm Password',
    'register.invite': 'Invite Code (optional)',
    'register.agree': 'I agree to the Terms of Service and Privacy Policy',
    'register.button': 'Register',
    'register.haveAccount': 'Already have an account?',
    'recharge.title': 'Deposit',
    'recharge.time': 'Service hours: 09:00-22:00',
    'recharge.balance': 'Balance',
    'recharge.amount': 'Select Amount',
    'recharge.method': 'Payment Method',
    'recharge.submit': 'Contact Customer Service',
    'withdraw.title': 'Withdraw',
    'withdraw.balance': 'Available Balance',
    'withdraw.card': 'Select Bank Card',
    'withdraw.amount': 'Amount',
    'withdraw.all': 'Withdraw All',
    'withdraw.submit': 'Submit Request',
    'position.title': 'Positions',
    'position.total': 'Total Position Value',
    'position.add': 'Add',
    'position.reduce': 'Reduce',
    'position.close': 'Close',
    'account.title': 'Account',
    'account.nickname': 'Nickname',
    'account.phone': 'Phone',
    'account.changePw': 'Change Password',
    'account.realName': 'Identity Verification',
    'account.logout': 'Logout',
    'auth.title': 'Identity Verification',
    'auth.unverified': 'Unverified',
    'auth.pending': 'Pending',
    'auth.verified': 'Verified',
    'auth.rejected': 'Rejected',
    'auth.name': 'Real Name',
    'auth.idCard': 'ID Number',
    'auth.front': 'ID Front',
    'auth.back': 'ID Back',
    'auth.hold': 'Hold ID Photo',
    'auth.submit': 'Submit',
    'bank.title': 'Bank Cards',
    'bank.add': 'Add Card',
    'bank.default': 'Default',
    'footer.about': 'About Us',
    'footer.trade': 'Trading Services',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© 2026 HKEX. All rights reserved.',
    'footer.risk': 'Investment involves risks. Please invest cautiously.',
    'footer.icp': 'ICP License: Guangdong ICP 2026123456',
    'footer.license': 'Licensed by the Securities and Futures Commission of Hong Kong',
    'market.title': 'Market Center',
    'market.search': 'Search stock code or name',
    'stock.buy': 'Buy',
    'stock.sell': 'Sell',
    'stock.favorite': 'Favorite',
    'news.title': 'News Center',
    'ipo.title': 'IPO Calendar',
    'study.title': 'Investor Academy',
    'tools.title': 'Smart Tools',
    'about.title': 'About Platform',
    'service.title': 'Customer Service',
    'points.title': 'Points Mall',
    'asset.title': 'Asset Wallet',
    'index.indices': 'Major Indices',
    'index.ranking': 'Stock Ranking',
    'index.news': '7x24 News',
    'index.calendar': 'Trading Calendar',
    'index.quick': 'Quick Access',
  }
}

interface LangContextType {
  lang: Lang
  t: (key: string) => string
  setLang: (l: Lang) => void
}

const Context = createContext<LangContextType>({
  lang: 'zh-TW',
  t: (key: string) => key,
  setLang: () => {}
})

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem('lang') as Lang) || 'zh-TW'
  })

  const t = (key: string) => translations[lang][key] || key

  const changeLang = (l: Lang) => {
    localStorage.setItem('lang', l)
    setLang(l)
  }

  return (
    <Context.Provider value={{ lang, t, setLang: changeLang }}>
      {children}
    </Context.Provider>
  )
}

export const useLang = () => useContext(Context)
